import commandRoom from '../../../projects/polaxory/command_room.json';

type Audience = { name: string; value: string };
type Signal = { lane: string; label: string; state: string };
type Operator = { name: string; purpose: string; status: string };

function Badge({ children }: { children: React.ReactNode }) {
  return (
    <span style={{ border: '1px solid #d7d7d7', borderRadius: 999, padding: '4px 10px', fontSize: 12 }}>
      {children}
    </span>
  );
}

export default function PolaxoryProjectPage() {
  const project = commandRoom;

  return (
    <main style={{ maxWidth: 1120, margin: '0 auto', padding: '48px 24px', fontFamily: 'Inter, system-ui, sans-serif' }}>
      <section style={{ display: 'grid', gap: 20, marginBottom: 36 }}>
        <Badge>{project.route}</Badge>
        <h1 style={{ fontSize: 48, lineHeight: 1, margin: 0 }}>Polaxory Command Room</h1>
        <p style={{ fontSize: 20, maxWidth: 820, color: '#444', margin: 0 }}>{project.mission}</p>
        <p style={{ fontSize: 16, maxWidth: 820, color: '#666', margin: 0 }}>{project.thesis}</p>
        <button style={{ width: 'fit-content', border: 0, borderRadius: 12, padding: '12px 18px', background: '#111', color: '#fff', fontWeight: 700 }}>
          Continue Shipping
        </button>
      </section>

      <section style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1.2fr) minmax(320px, 0.8fr)', gap: 20, alignItems: 'start' }}>
        <article style={{ border: '1px solid #e8e8e8', borderRadius: 20, padding: 24 }}>
          <Badge>Next profitable ship</Badge>
          <h2 style={{ fontSize: 30, marginBottom: 8 }}>{project.nextProfitableShip.title}</h2>
          <p style={{ color: '#444' }}>{project.nextProfitableShip.why}</p>
          <ul>
            <li><strong>Expected impact:</strong> {project.nextProfitableShip.expectedImpact}</li>
            <li><strong>Risk:</strong> {project.nextProfitableShip.risk}</li>
            <li><strong>Status:</strong> {project.nextProfitableShip.status}</li>
          </ul>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 16 }}>
            {project.nextProfitableShip.actions.map((action: string) => <Badge key={action}>{action}</Badge>)}
          </div>
        </article>

        <aside style={{ border: '1px solid #e8e8e8', borderRadius: 20, padding: 24, background: '#fafafa' }}>
          <Badge>Task generated by Continue Shipping</Badge>
          <h3>{project.continueShipping.task.title}</h3>
          <p style={{ color: '#555' }}>{project.continueShipping.task.description}</p>
          <ul>
            {project.continueShipping.task.acceptanceCriteria.map((item: string) => <li key={item}>{item}</li>)}
          </ul>
        </aside>
      </section>

      <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16, marginTop: 24 }}>
        {project.audiences.map((audience: Audience) => (
          <article key={audience.name} style={{ border: '1px solid #e8e8e8', borderRadius: 16, padding: 18 }}>
            <h3>{audience.name}</h3>
            <p style={{ color: '#555' }}>{audience.value}</p>
          </article>
        ))}
      </section>

      <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 20, marginTop: 24 }}>
        <article style={{ border: '1px solid #e8e8e8', borderRadius: 20, padding: 24 }}>
          <h2>Signals</h2>
          {project.signals.map((signal: Signal) => (
            <p key={`${signal.lane}-${signal.label}`}>
              <strong>{signal.lane}</strong>: {signal.label} <Badge>{signal.state}</Badge>
            </p>
          ))}
        </article>

        <article style={{ border: '1px solid #e8e8e8', borderRadius: 20, padding: 24 }}>
          <h2>Operators</h2>
          {project.operators.map((operator: Operator) => (
            <p key={operator.name}>
              <strong>{operator.name}</strong> <Badge>{operator.status}</Badge><br />
              <span style={{ color: '#555' }}>{operator.purpose}</span>
            </p>
          ))}
        </article>
      </section>
    </main>
  );
}
